# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtsk_treeseq_init_variants_iterator <- function(ts, samples = NULL, isolated_as_missing = TRUE, alleles = NULL, left = 0.0, right = NA_real_) {
    .Call(`_RcppTskit_rtsk_treeseq_init_variants_iterator`, ts, samples, isolated_as_missing, alleles, left, right)
}

rtsk_treeseq_next_variant <- function(iterator) {
    .Call(`_RcppTskit_rtsk_treeseq_next_variant`, iterator)
}

test_rtsk_variant_iterator_force_null_first_allele <- function(enabled) {
    invisible(.Call(`_RcppTskit_test_rtsk_variant_iterator_force_null_first_allele`, enabled))
}

test_rtsk_variant_iterator_set_site_bounds <- function(iterator, next_site_id, stop_site_id) {
    invisible(.Call(`_RcppTskit_test_rtsk_variant_iterator_set_site_bounds`, iterator, next_site_id, stop_site_id))
}

test_variant_site_index_range <- function(start, stop) {
    invisible(.Call(`_RcppTskit_test_variant_site_index_range`, start, stop))
}

test_validate_options <- function(options, supported) {
    .Call(`_RcppTskit_test_validate_options`, options, supported)
}

test_rtsk_wrap_tsk_flags_as_int <- function(value) {
    .Call(`_RcppTskit_test_rtsk_wrap_tsk_flags_as_int`, value)
}

test_rtsk_wrap_tsk_size_t_as_integer64 <- function(value, force_range_error = FALSE) {
    .Call(`_RcppTskit_test_rtsk_wrap_tsk_size_t_as_integer64`, value, force_range_error)
}

#' @title Report the version of installed kastore C API
#' @details The version is stored in the installed header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_RcppTskit_kastore_version`)
}

#' @title Report the version of installed \code{tskit} C API
#' @details The version is defined in the installed header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_RcppTskit_tskit_version`)
}

rtsk_treeseq_load <- function(filename, options = 0L) {
    .Call(`_RcppTskit_rtsk_treeseq_load`, filename, options)
}

rtsk_table_collection_load <- function(filename, options = 0L) {
    .Call(`_RcppTskit_rtsk_table_collection_load`, filename, options)
}

rtsk_treeseq_dump <- function(ts, filename, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_treeseq_dump`, ts, filename, options))
}

rtsk_table_collection_dump <- function(tc, filename, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_table_collection_dump`, tc, filename, options))
}

rtsk_treeseq_copy_tables <- function(ts, options = 0L) {
    .Call(`_RcppTskit_rtsk_treeseq_copy_tables`, ts, options)
}

rtsk_treeseq_init <- function(tc, options = 0L) {
    .Call(`_RcppTskit_rtsk_treeseq_init`, tc, options)
}

rtsk_treeseq_get_num_provenances <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_provenances`, ts)
}

rtsk_treeseq_get_num_populations <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_populations`, ts)
}

rtsk_treeseq_get_num_migrations <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_migrations`, ts)
}

rtsk_treeseq_get_num_individuals <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_individuals`, ts)
}

rtsk_treeseq_get_num_samples <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_samples`, ts)
}

rtsk_treeseq_get_samples <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_samples`, ts)
}

rtsk_treeseq_get_sample_node_data <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_sample_node_data`, ts)
}

rtsk_treeseq_get_num_nodes <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_nodes`, ts)
}

rtsk_treeseq_get_num_edges <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_edges`, ts)
}

rtsk_treeseq_get_num_trees <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_trees`, ts)
}

rtsk_treeseq_get_num_sites <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_sites`, ts)
}

rtsk_treeseq_get_num_mutations <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_num_mutations`, ts)
}

rtsk_treeseq_get_sequence_length <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_sequence_length`, ts)
}

rtsk_treeseq_get_discrete_genome <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_discrete_genome`, ts)
}

rtsk_treeseq_has_reference_sequence <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_has_reference_sequence`, ts)
}

rtsk_treeseq_get_time_units <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_time_units`, ts)
}

rtsk_treeseq_get_discrete_time <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_discrete_time`, ts)
}

rtsk_treeseq_get_min_time <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_min_time`, ts)
}

rtsk_treeseq_get_max_time <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_max_time`, ts)
}

rtsk_treeseq_get_file_uuid <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_get_file_uuid`, ts)
}

rtsk_treeseq_summary <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_summary`, ts)
}

rtsk_treeseq_metadata_length <- function(ts) {
    .Call(`_RcppTskit_rtsk_treeseq_metadata_length`, ts)
}

rtsk_table_collection_get_num_provenances <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_num_provenances`, tc)
}

rtsk_table_collection_get_num_populations <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_num_populations`, tc)
}

rtsk_table_collection_get_num_migrations <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_num_migrations`, tc)
}

rtsk_table_collection_get_num_individuals <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_num_individuals`, tc)
}

rtsk_table_collection_get_num_nodes <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_num_nodes`, tc)
}

rtsk_table_collection_get_num_edges <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_num_edges`, tc)
}

rtsk_table_collection_get_num_sites <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_num_sites`, tc)
}

rtsk_table_collection_get_num_mutations <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_num_mutations`, tc)
}

rtsk_table_collection_get_sequence_length <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_sequence_length`, tc)
}

rtsk_table_collection_has_reference_sequence <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_has_reference_sequence`, tc)
}

rtsk_table_collection_get_time_units <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_time_units`, tc)
}

rtsk_table_collection_get_file_uuid <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_get_file_uuid`, tc)
}

rtsk_table_collection_has_index <- function(tc, options = 0L) {
    .Call(`_RcppTskit_rtsk_table_collection_has_index`, tc, options)
}

rtsk_table_collection_build_index <- function(tc, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_table_collection_build_index`, tc, options))
}

rtsk_table_collection_drop_index <- function(tc, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_table_collection_drop_index`, tc, options))
}

rtsk_table_collection_sort <- function(tc, start_edges = 0L, start_sites = 0L, start_mutations = 0L, options = 0L) {
    invisible(.Call(`_RcppTskit_rtsk_table_collection_sort`, tc, start_edges, start_sites, start_mutations, options))
}

rtsk_table_collection_simplify <- function(tc, samples = NULL, options = 0L) {
    .Call(`_RcppTskit_rtsk_table_collection_simplify`, tc, samples, options)
}

rtsk_table_collection_summary <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_summary`, tc)
}

rtsk_table_collection_metadata_length <- function(tc) {
    .Call(`_RcppTskit_rtsk_table_collection_metadata_length`, tc)
}

rtsk_individual_table_add_row <- function(tc, flags = 0L, location = NULL, parents = NULL, metadata = NULL) {
    .Call(`_RcppTskit_rtsk_individual_table_add_row`, tc, flags, location, parents, metadata)
}

rtsk_individual_table_get_row <- function(tc, index) {
    .Call(`_RcppTskit_rtsk_individual_table_get_row`, tc, index)
}

rtsk_node_table_add_row <- function(tc, flags = 0L, time = 0, population = -1L, individual = -1L, metadata = NULL) {
    .Call(`_RcppTskit_rtsk_node_table_add_row`, tc, flags, time, population, individual, metadata)
}

rtsk_node_table_get_row <- function(tc, index) {
    .Call(`_RcppTskit_rtsk_node_table_get_row`, tc, index)
}

rtsk_edge_table_add_row <- function(tc, left, right, parent, child, metadata = NULL) {
    .Call(`_RcppTskit_rtsk_edge_table_add_row`, tc, left, right, parent, child, metadata)
}

rtsk_edge_table_get_row <- function(tc, index) {
    .Call(`_RcppTskit_rtsk_edge_table_get_row`, tc, index)
}

rtsk_site_table_add_row <- function(tc, position, ancestral_state, metadata = NULL) {
    .Call(`_RcppTskit_rtsk_site_table_add_row`, tc, position, ancestral_state, metadata)
}

rtsk_site_table_get_row <- function(tc, index) {
    .Call(`_RcppTskit_rtsk_site_table_get_row`, tc, index)
}

rtsk_mutation_table_add_row <- function(tc, site, node, parent, time, derived_state, metadata = NULL) {
    .Call(`_RcppTskit_rtsk_mutation_table_add_row`, tc, site, node, parent, time, derived_state, metadata)
}

rtsk_mutation_table_get_row <- function(tc, index) {
    .Call(`_RcppTskit_rtsk_mutation_table_get_row`, tc, index)
}

rtsk_population_table_add_row <- function(tc, metadata = NULL) {
    .Call(`_RcppTskit_rtsk_population_table_add_row`, tc, metadata)
}

rtsk_population_table_get_row <- function(tc, index) {
    .Call(`_RcppTskit_rtsk_population_table_get_row`, tc, index)
}

rtsk_migration_table_add_row <- function(tc, left, right, node, source, dest, time, metadata = NULL) {
    .Call(`_RcppTskit_rtsk_migration_table_add_row`, tc, left, right, node, source, dest, time, metadata)
}

rtsk_migration_table_get_row <- function(tc, index) {
    .Call(`_RcppTskit_rtsk_migration_table_get_row`, tc, index)
}

rtsk_provenance_table_add_row <- function(tc, timestamp, record) {
    .Call(`_RcppTskit_rtsk_provenance_table_add_row`, tc, timestamp, record)
}

rtsk_provenance_table_get_row <- function(tc, index) {
    .Call(`_RcppTskit_rtsk_provenance_table_get_row`, tc, index)
}

test_tsk_bug_assert_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_c`))
}

test_tsk_bug_assert_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_cpp`))
}

test_tsk_trace_error_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_c`))
}

test_tsk_trace_error_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_cpp`))
}

tsk_trace_errors_defined <- function() {
    .Call(`_RcppTskit_tsk_trace_errors_defined`)
}

test_rtsk_treeseq_copy_tables_forced_error <- function(ts) {
    .Call(`_RcppTskit_test_rtsk_treeseq_copy_tables_forced_error`, ts)
}

test_rtsk_treeseq_init_forced_error <- function(tc) {
    .Call(`_RcppTskit_test_rtsk_treeseq_init_forced_error`, tc)
}

test_rtsk_table_collection_build_index_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_table_collection_build_index_forced_error`, tc))
}

test_rtsk_individual_table_add_row_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_individual_table_add_row_forced_error`, tc))
}

test_rtsk_node_table_add_row_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_node_table_add_row_forced_error`, tc))
}

test_rtsk_edge_table_add_row_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_edge_table_add_row_forced_error`, tc))
}

test_rtsk_site_table_add_row_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_site_table_add_row_forced_error`, tc))
}

test_rtsk_mutation_table_add_row_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_mutation_table_add_row_forced_error`, tc))
}

test_rtsk_population_table_add_row_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_population_table_add_row_forced_error`, tc))
}

test_rtsk_migration_table_add_row_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_migration_table_add_row_forced_error`, tc))
}

test_rtsk_provenance_table_add_row_forced_error <- function(tc) {
    invisible(.Call(`_RcppTskit_test_rtsk_provenance_table_add_row_forced_error`, tc))
}

